### ISSUE TITLE
Учесть замечания к предыдущему проекту

### ISSUE THREAD

**Issue by coursar** [rustamSurmashev/Oboi#1]
https://github.com/rustamSurmashev/homework_1/issues

**Comment by rustamSurmashev** [comment]
@coursar, данное ДЗ выполнено:

изменено название репозитория
использован хороший файл .гитигнор (который не игнорирует джейсоны)
добавлен файл zodiac-app.js
добавлен Travis CI
добавлен CodeCov (100 %)

**Comment by coursar** [comment]
Отлично
