### ISSUE TITLE
Переименовать переменные - не используйте транслит!

### ISSUE THREAD

**Issue by coursar** [rustamSurmashev/Oboi#3]
https://github.com/rustamSurmashev/Oboi/blob/e36cf7230c7fd703f21e23066be78e5c9bcf8da8/src/js/oboi.js#L2-L12

**Comment by rustamSurmashev** [comment]
В проекте применены реальные английские слова. 
Выполнено в 79ee59570e829f6a27a1cf165835b3d349632b8c.
